"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AgendaEvent, AGENDA_STATUSES } from "@/lib/agenda";

const blank = (): AgendaEvent => ({ id: crypto.randomUUID(), date: "", time: "", name: "", format: "", space: "", status: "Confirmado", description: "" });

export default function AgendaAdmin() {
  const [events, setEvents] = useState<AgendaEvent[]>([]), [editing, setEditing] = useState<AgendaEvent | null>(null), [message, setMessage] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/admin/agenda", { cache: "no-store" }).then(async (response) => { if (response.status === 401) return window.location.assign("/admin"); const body = await response.json(); if (!response.ok) throw new Error(body.error); setEvents(body.events); }).catch((error) => setMessage(error.message || "No se pudo cargar la agenda.")).finally(() => setLoading(false)); }, []);
  const sorted = useMemo(() => [...events].sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), [events]);
  const update = (field: keyof AgendaEvent, value: string) => setEditing((current) => current ? { ...current, [field]: value } : current);
  const keep = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; setEvents((current) => current.some(({ id }) => id === editing.id) ? current.map((item) => item.id === editing.id ? editing : item) : [...current, editing]); setEditing(null); };
  const save = async () => { setSaving(true); setMessage(""); const response = await fetch("/api/admin/agenda", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ events }) }); const body = await response.json().catch(() => ({})); if (response.status === 401) return window.location.assign("/admin"); if (!response.ok) { setMessage(body.error || "No se pudo guardar."); setSaving(false); return; } setEvents(body.events); setMessage("Agenda publicada. La home ya muestra estos cambios."); setSaving(false); };
  const logout = async () => { await fetch("/api/admin/logout", { method: "POST" }); window.location.assign("/admin"); };
  return <main className="admin-shell admin-agenda"><header><a className="admin-brand" href="/"><span>i</span>MERGE <small>CORPORATE CENTER</small></a><div><a href="/" target="_blank">Ver home ↗</a><button onClick={logout}>Cerrar sesión</button></div></header><section className="admin-title"><p className="eyebrow">AGENDA PÚBLICA</p><h1>Próximos<br/><em>eventos.</em></h1><p>Los cambios se publican para todos los visitantes al presionar guardar.</p></section><section className="admin-workspace"><div className="admin-list"><div className="admin-list-head"><h2>Eventos</h2><button className="button lime" onClick={() => setEditing(blank())}>+ Nuevo evento</button></div>{loading ? <p>Cargando agenda…</p> : sorted.map((item) => <article key={item.id}><time>{item.date}<b>{item.time}</b></time><div><strong>{item.name}</strong><span>{item.format} · {item.space}</span></div><i>{item.status}</i><button onClick={() => setEditing(item)}>Editar</button><button className="delete" onClick={() => setEvents((current) => current.filter(({ id }) => id !== item.id))}>Eliminar</button></article>)}{!loading && !sorted.length && <p>No hay eventos cargados todavía.</p>}</div><aside className="admin-editor">{editing ? <form onSubmit={keep}><div className="editor-head"><h2>{events.some(({ id }) => id === editing.id) ? "Editar evento" : "Nuevo evento"}</h2><button type="button" onClick={() => setEditing(null)}>×</button></div><label>Nombre del evento<input value={editing.name} onChange={(event) => update("name", event.target.value)} required /></label><div className="admin-row"><label>Fecha<input type="date" value={editing.date} onChange={(event) => update("date", event.target.value)} required /></label><label>Horario<input type="time" value={editing.time} onChange={(event) => update("time", event.target.value)} required /></label></div><label>Tipo / formato<input value={editing.format} onChange={(event) => update("format", event.target.value)} placeholder="Conferencia, Networking…" required /></label><label>Espacio<input value={editing.space} onChange={(event) => update("space", event.target.value)} required /></label><label>Estado<select value={editing.status} onChange={(event) => update("status", event.target.value)}>{AGENDA_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label>Descripción <small>(opcional)</small><textarea value={editing.description || ""} rows={4} onChange={(event) => update("description", event.target.value)} /></label><button className="button dark">Guardar en la lista</button></form> : <div className="admin-empty"><p className="eyebrow">LISTO PARA EDITAR</p><h2>Elegí un evento<br/><em>o creá uno nuevo.</em></h2></div>}</aside></section><footer className="admin-save"><p>{message || "Primero guardá cada evento en la lista. Después, publicá la agenda."}</p><button className="button lime" disabled={saving || loading} onClick={save}>{saving ? "Publicando…" : "Publicar cambios →"}</button></footer></main>;
}
