"use client";

import { useEffect, useMemo, useState } from "react";

type Dimension = { id: string; name: string; color: string };
type Person = { id: number; industry: string; role: string; experience: string; scores: Record<string, number>; scoreGeneral?: number | null; maturityLevel?: string; open: string };

const dimensions: Dimension[] = [
  { id: "strategy", name: "Estrategia & Visión", color: "#7967ff" },
  { id: "governance", name: "Gobernanza & CoE", color: "#f5a44b" },
  { id: "data", name: "Datos & Tecnología", color: "#32b89a" },
  { id: "talent", name: "Talento & Cultura", color: "#40a0ff" },
  { id: "adoption", name: "Adopción & Escala", color: "#e56f9a" }
];
const levels = ["Explorando", "Construyendo", "Escalando", "Transformando"];
const mean = (values: number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
const demo: Person[] = Array.from({ length: 56 }, (_, index) => {
  const bases = [11.5, 8.2, 11.7, 10.1, 8.9];
  const scores = Object.fromEntries(dimensions.map((dimension, position) => [dimension.id, Math.min(5, Math.max(1, (bases[position] + ((index * (position + 3)) % 7 - 3) * .52) / 4))]));
  const general = Math.round(mean(Object.values(scores)) * 20);
  return { id: index + 1, industry: ["Finanzas", "Tecnología", "Servicios", "Industria"][index % 4], role: ["Dirección", "Gerencia", "Especialista"][index % 3], experience: ["Alta", "Media", "Inicial"][index % 3], scores, scoreGeneral: general, maturityLevel: general < 45 ? "Explorando" : general < 65 ? "Construyendo" : "Escalando", open: "" };
});

function Radar({ values }: { values: { dimension: Dimension; value: number }[] }) {
  const point = (value: number, i: number, r = 40) => { const a = (Math.PI * 2 * i) / values.length - Math.PI / 2; const radius = r * value / 5; return `${50 + radius * Math.cos(a)},${50 + radius * Math.sin(a)}`; };
  return <svg viewBox="0 0 100 100" className="radar" aria-label="Radar de las cinco dimensiones">{[10, 20, 30, 40].map((r) => <circle key={r} cx="50" cy="50" r={r} fill="none" stroke="currentColor" opacity=".12" />)}<polygon points={values.map(({ value }, i) => point(value, i)).join(" ")} fill="rgba(121,103,255,.25)" stroke="#7967ff" strokeWidth="1.7" />{values.map(({ dimension }, i) => { const a = (Math.PI * 2 * i) / values.length - Math.PI / 2; return <text key={dimension.id} x={50 + 48 * Math.cos(a)} y={50 + 48 * Math.sin(a)} textAnchor="middle">{dimension.name.split(" ")[0]}</text>; })}</svg>;
}

export default function Home() {
  const [people, setPeople] = useState(demo); const [source, setSource] = useState<"demo" | "real">("demo"); const [scene, setScene] = useState(0);
  const [showImport, setShowImport] = useState(false); const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [prediction, setPrediction] = useState<string | null>(null); const [narration, setNarration] = useState("");
  useEffect(() => setUrl(localStorage.getItem("maturity-sheet-url") ?? ""), []);
  const scores = useMemo(() => dimensions.map((dimension) => ({ dimension, value: mean(people.map((person) => person.scores[dimension.id]).filter(Number.isFinite)) })), [people]);
  const general = Math.round(mean(people.map((person) => person.scoreGeneral ?? mean(Object.values(person.scores)) * 20)));
  const levelCounts = useMemo(() => levels.map((level) => ({ level, count: people.filter((person) => person.maturityLevel === level).length })), [people]);
  const sorted = [...scores].sort((a, b) => b.value - a.value); const strongest = sorted[0]; const opportunity = sorted[sorted.length - 1];
  const importData = async () => { setLoading(true); setMessage(""); try { const response = await fetch("/api/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setPeople(result.participants); setSource("real"); localStorage.setItem("maturity-sheet-url", url); setMessage(`Actualizado: ${result.summary.rows} respuestas reales.`); setScene(0); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo actualizar."); } finally { setLoading(false); } };
  const explain = () => { const focus = scene === 3 ? `El perfil muestra una fortaleza relativa en ${strongest.dimension.name} (${(strongest.value * 4).toFixed(1)}/20) y una oportunidad en ${opportunity.dimension.name} (${(opportunity.value * 4).toFixed(1)}/20).` : scene === 5 ? `La tensión principal surge entre ${strongest.dimension.name} y ${opportunity.dimension.name}, con una brecha de ${((strongest.value - opportunity.value) * 4).toFixed(1)} puntos sobre 20.` : `El score general del grupo es ${general}/100, calculado sobre ${people.length} respuestas.`; setNarration(`${focus} Esto importa porque la adopción de AI combina dirección, capacidades y uso sostenido. Es una lectura descriptiva: no permite inferir causalidad. Pregunta para abrir el debate: ¿qué práctica concreta ayudaría a cerrar esta brecha?`); };
  const pages = [
    <Cover key="cover" general={general} count={people.length} source={source} onStart={() => setScene(1)} />,
    <Overview key="overview" general={general} levels={levelCounts} />, <Prediction key="prediction" selected={prediction} select={setPrediction} />, <Profile key="profile" scores={scores} />, <Rank key="rank" scores={sorted} />, <Tension key="tension" strongest={strongest} opportunity={opportunity} />, <Compare key="compare" people={people} />, <Closing key="closing" strongest={strongest} opportunity={opportunity} general={general} />
  ];
  return <main><header><div className="logo"><span>✦</span> AI maturity <small>Di Tella</small></div><div className="source-badge"><i /> {source === "real" ? "Planilla real" : "Datos de demostración"}</div><button className="narrate" onClick={explain}>✦ Explicar esta vista</button><button className="refresh" onClick={() => setShowImport(true)}>↻ Actualizar datos</button></header>
    {showImport && <section className="import"><div><b>Conectar planilla pública</b><p>Pegá el enlace de Google Sheets. Se importan únicamente los siete indicadores acordados.</p></div><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://docs.google.com/spreadsheets/d/..." /><button onClick={importData} disabled={loading}>{loading ? "Actualizando…" : "Actualizar"}</button><button className="close" onClick={() => setShowImport(false)}>×</button>{message && <small>{message}</small>}</section>}
    {narration && <aside className="narration"><button onClick={() => setNarration("")}>×</button><p>GUION DEL DOCENTE · 30 SEGUNDOS</p><strong>{narration}</strong></aside>}<section className="stage">{pages[scene]}</section><footer><div className="progress">{pages.map((_, index) => <button aria-label={`Escena ${index + 1}`} key={index} className={index === scene ? "current" : ""} onClick={() => setScene(index)} />)}</div><span>{scene + 1} / {pages.length}</span><div><button disabled={!scene} onClick={() => setScene(scene - 1)}>← Anterior</button><button className="next" disabled={scene === pages.length - 1} onClick={() => setScene(scene + 1)}>Siguiente →</button></div></footer></main>;
}

function Cover({ general, count, source, onStart }: { general: number; count: number; source: string; onStart: () => void }) { return <div className="cover"><p>MAESTRÍA · ADOPCIÓN ORGANIZACIONAL DE AI</p><h1>Madurez y adopción<br/>de AI</h1><h2>Una conversación a partir de las respuestas de la clase.</h2><div className="cover-score"><strong>{general}</strong><span>score general<br/>sobre 100</span></div><div className="cover-meta"><span>{count} respuestas</span><span>{source === "real" ? "Fuente actualizada" : "Modo demostración"}</span></div><button className="start" onClick={onStart}>Comenzar exploración <b>→</b></button></div>; }
function Overview({ general, levels }: { general: number; levels: { level: string; count: number }[] }) { return <div className="scene"><p className="kicker">01 · RESULTADO GENERAL</p><h1>El grupo se encuentra en una etapa de <em>{general < 45 ? "exploración" : general < 65 ? "construcción" : "escalamiento"}.</em></h1><div className="overview"><div className="big-score"><strong>{general}</strong><span>/100</span><small>Score general promedio</small></div><div className="levels">{levels.map(({ level, count }) => <div key={level}><span>{level}</span><i style={{ width: `${Math.max(4, count * 100 / Math.max(1, levels.reduce((sum, item) => sum + item.count, 0)))}%` }} /><b>{count}</b></div>)}</div></div><p className="note">El score resume percepciones del grupo; no equivale a una auditoría organizacional.</p></div>; }
function Prediction({ selected, select }: { selected: string | null; select: (value: string) => void }) { const options = ["Estrategia & Visión", "Talento & Cultura", "Adopción & Escala"]; return <div className="scene prediction"><p className="kicker">02 · PREDICCIÓN DEL CURSO</p><h1>Antes de revelar el perfil,<br/><em>hagamos una apuesta.</em></h1><p>¿Cuál creen que es hoy la dimensión más madura del grupo?</p><div className="prediction-options">{options.map((option) => <button className={selected === option ? "chosen" : ""} key={option} onClick={() => select(option)}><span>{selected === option ? "✓" : ""}</span>{option}</button>)}</div>{selected && <p className="prediction-note">Elegiste “{selected}”. En la siguiente escena, compará la intuición del grupo con la evidencia.</p>}</div>; }
function Profile({ scores }: { scores: { dimension: Dimension; value: number }[] }) { return <div className="scene"><p className="kicker">02 · PERFIL DE MADUREZ</p><h1>Cinco dimensiones.<br/><em>Una conversación más completa.</em></h1><div className="profile"><Radar values={scores} /><div>{scores.map(({ dimension, value }) => <div className="legend" key={dimension.id}><i style={{ background: dimension.color }} /><span>{dimension.name}</span><b>{(value * 4).toFixed(1)}<small>/20</small></b></div>)}</div></div></div>; }
function Rank({ scores }: { scores: { dimension: Dimension; value: number }[] }) { return <div className="scene"><p className="kicker">03 · FORTALEZAS Y OPORTUNIDADES</p><h1>¿Dónde está hoy la energía?<br/><em>¿Dónde está el trabajo pendiente?</em></h1><div className="ranking">{scores.map(({ dimension, value }, index) => <div className="rank" key={dimension.id}><span className="number">0{index + 1}</span><span className="rank-name">{dimension.name}</span><div><i style={{ width: `${value * 20}%`, background: dimension.color }} /></div><b>{(value * 4).toFixed(1)}<small>/20</small></b></div>)}</div></div>; }
function Tension({ strongest, opportunity }: { strongest: { dimension: Dimension; value: number }; opportunity: { dimension: Dimension; value: number } }) { const gap = ((strongest.value - opportunity.value) * 4).toFixed(1); return <div className="scene tension"><p className="kicker">05 · LA TENSIÓN DEL DÍA</p><h1>¿Cómo puede coexistir<br/><em>esto con esto?</em></h1><div className="tension-cards"><article><span>FORTALEZA RELATIVA</span><b>{strongest.dimension.name}</b><strong>{(strongest.value * 4).toFixed(1)}<small>/20</small></strong></article><div className="versus">VS<small>{gap} pts de brecha</small></div><article><span>OPORTUNIDAD</span><b>{opportunity.dimension.name}</b><strong>{(opportunity.value * 4).toFixed(1)}<small>/20</small></strong></article></div><p className="debate">Pregunta al curso: ¿qué prácticas organizacionales podrían explicar esta diferencia sin asumir causalidad?</p></div>; }
function Compare({ people }: { people: Person[] }) { const groups = [...new Set(people.map((person) => person.industry))].filter((industry) => people.filter((person) => person.industry === industry).length >= 3).slice(0, 4).map((industry) => ({ industry, score: Math.round(mean(people.filter((person) => person.industry === industry).map((person) => person.scoreGeneral ?? mean(Object.values(person.scores)) * 20))), count: people.filter((person) => person.industry === industry).length })); return <div className="scene"><p className="kicker">04 · PERSPECTIVAS</p><h1>La madurez también<br/><em>cambia según el contexto.</em></h1><div className="group-cards">{groups.map((group) => <article key={group.industry}><small>{group.count} respuestas</small><strong>{group.score}</strong><span>{group.industry}</span><i style={{ width: `${group.score}%` }} /></article>)}</div><p className="note">Solo se muestran grupos con al menos tres respuestas; las diferencias son descriptivas.</p></div>; }
function Closing({ strongest, opportunity, general }: { strongest: { dimension: Dimension; value: number }; opportunity: { dimension: Dimension; value: number }; general: number }) { return <div className="scene closing"><p className="kicker">05 · CIERRE</p><h1>Del diagnóstico<br/>a la conversación.</h1><div className="takeaways"><article><span>FORTALEZA RELATIVA</span><b>{strongest.dimension.name}</b><strong>{(strongest.value * 4).toFixed(1)}<small>/20</small></strong></article><article><span>OPORTUNIDAD PRIORITARIA</span><b>{opportunity.dimension.name}</b><strong>{(opportunity.value * 4).toFixed(1)}<small>/20</small></strong></article><article><span>PREGUNTA PARA EL CURSO</span><b>¿Qué práctica tendría el mayor efecto para llevar el score de {general} a la siguiente etapa?</b></article></div></div>; }
